package electronicshop;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Admin extends User {
    private final String accessLevel;

    public Admin(String username, String password, String email, String accessLevel) {
        super(username, password, email);
        this.accessLevel = accessLevel;
    }

    public void manageInventory(Inventory inventory, Product product, int quantity) {
        if (!"MANAGER".equals(accessLevel)) {
            System.out.println("Insufficient privileges to manage inventory.");
            return;
        }
        inventory.updateProductStock(product, quantity);
        System.out.println("Updated stock for " + product.getName() + " to " + quantity + " units.");
    }

    public void generateRevenueReport() {
        // Generate timestamp (European!)
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String timestamp = dateFormat.format(new Date());

        System.out.println("\n==== REVENUE REPORT ====");
        System.out.println("Generated by: " + getUsername());
        System.out.println("Date and Time: " + timestamp);
        System.out.println("Total Revenue: €" + String.format("%.2f", ElectronicShopSystem.getTotalRevenue()));
        System.out.println("=======================");
    }
}